# Generated by Django 6.0.6 on 2026-06-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('jobseeker', 'Job Seeker')], default='jobseeker', max_length=20),
            preserve_default=False,
        ),
    ]
